const SET_POETRY_LIST = 'SET_POETRY_LIST'
const SET_POETRY_ITEM = 'SET_POETRY_ITEM'
const SET_USER_INFO = 'SET_USER_INFO'
const SET_COMMENT_LIST = 'SET_COMMENT_LIST'
const SET_MSG_LIST = 'SET_MSG_LIST'
const SET_CHAT_LIST = 'SET_CHAT_LIST'
const SET_UNREAD = 'SET_UNREAD'
const SET_USERS = 'SET_USERS'

export {
  SET_POETRY_LIST,
  SET_POETRY_ITEM,
  SET_USER_INFO,
  SET_COMMENT_LIST,
  SET_MSG_LIST,
  SET_CHAT_LIST,
  SET_UNREAD,
  SET_USERS
}
